name: Deploy Flask App

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests (пример теста)
      run: |
        python -m pytest tests/ || echo "No tests found"

    - name: Build and run with Docker Compose
      run: |
        docker-compose up -d --build
        sleep 10  # Даем время приложению запуститься
        curl --fail http://localhost:5000 || exit 1
